# Generated by Django 5.2.7 on 2026-04-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('classic', 'NPV/ROI/IRR'), ('monte_carlo', 'Monte Carlo'), ('saas', 'SaaS metrikalari'), ('risk_matrix', 'Risk matritsasi'), ('forecast', 'Bashorat'), ('dynamic_risk', 'Dinamik eksport foydasi'), ('tax_shield', 'IT Park soliq imtiyozi'), ('rohc', 'ROHC'), ('bpo_uz', "O'zbekiston BPO eksport"), ('sustainability', 'Barqarorlik indeksi')], max_length=32)),
                ('parameters', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects.investmentproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('inputs', models.JSONField(default=dict)),
                ('last_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.investmentproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportTimeSeriesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('export_value_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_series', to='projects.investmentproject')),
            ],
            options={
                'ordering': ['period'],
                'constraints': [models.UniqueConstraint(fields=('project', 'period'), name='uniq_project_export_period')],
            },
        ),
    ]
