# Generated by Django 5.2.7 on 2026-04-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='kind',
            field=models.CharField(choices=[('classic', 'NPV/ROI/IRR'), ('monte_carlo', 'Monte Carlo'), ('saas', 'SaaS metrikalari'), ('risk_matrix', 'Risk matritsasi'), ('forecast', 'Bashorat'), ('dynamic_risk', 'Dinamik eksport foydasi'), ('tax_shield', 'IT Park soliq imtiyozi'), ('rohc', 'ROHC'), ('bpo_uz', "O'zbekiston BPO eksport"), ('sustainability', 'Barqarorlik indeksi'), ('sensitivity', 'Sensitivlik'), ('scenarios', 'Ssenariylar solishtirish'), ('monthly_dcf', 'Oylik DCF'), ('saas_extended', 'Rule40 / NRR / Unit'), ('risk_register', 'Risk reyestri'), ('fx_fetch', 'Valyuta kursi'), ('market_benchmark', 'Bozor benchmark')], max_length=32),
        ),
    ]
